## Tugas UAS Kecerdasan Buatan
### Nama : Mellinio Agung Wahyudi
### NIM : 09011381722135
### Kelas : SK 5A
# Classify Zoo Animals

In [6]:
import numpy as np
import pandas as pd

dataset = pd.read_csv("zoo.csv")
dataset.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [7]:
X = dataset.iloc[:, 1:17].values
y = dataset.iloc[:, -1].values

y[:][y[:]==7]=int(0)
X[:,12][X[:,12]==2]=int(1)
X[:,12][X[:,12]==4]=int(2)
X[:,12][X[:,12]==6]=int(3)
X[:,12][X[:,12]==8]=int(4)

y_som = y

from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X12 = onehotencoder.fit_transform(X[:, 12].reshape(-1, 1)).toarray()
y = onehotencoder.fit_transform(y.reshape(-1,1)).toarray()

y = np.asarray(y, dtype = int)
X12 = np.asarray(X12, dtype = int)
Xnew = np.append(X, X12, axis=1)
X = np.delete(Xnew, 12, axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

C:\Users\melli\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\melli\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
C:\Users\melli\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of in

In [9]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

classifier.add(Dense(units = 7, kernel_initializer = 'uniform', activation = 'relu', input_dim = 21))

classifier.add(Dense(units = 21, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 7, kernel_initializer = 'uniform', activation = 'softmax'))

classifier.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 200)

Epoch 1/200
80/80 [==============================] - 0s 3ms/step - loss: 1.9413 - accuracy: 0.3250
Epoch 2/200
80/80 [==============================] - 0s 450us/step - loss: 1.9299 - accuracy: 0.4250
Epoch 3/200
80/80 [==============================] - 0s 700us/step - loss: 1.9134 - accuracy: 0.4250
Epoch 4/200
80/80 [==============================] - 0s 450us/step - loss: 1.8912 - accuracy: 0.4250
Epoch 5/200
80/80 [==============================] - 0s 450us/step - loss: 1.8616 - accuracy: 0.4250
Epoch 6/200
80/80 [==============================] - 0s 600us/step - loss: 1.8236 - accuracy: 0.4250
Epoch 7/200
80/80 [==============================] - 0s 450us/step - loss: 1.7795 - accuracy: 0.4250
Epoch 8/200
80/80 [==============================] - 0s 600us/step - loss: 1.7281 - accuracy: 0.4250
Epoch 9/200
80/80 [==============================] - 0s 550us/step - loss: 1.6723 - accuracy: 0.4250
Epoch 10/200
80/80 [==============================] - 0s 450us/step - loss: 1.6110 - accuracy

In [10]:

y_pred = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)

y_pred_cat = np.argmax(y_pred, axis=1)
y_pred_test_cat = np.argmax(y_pred_test, axis=1)

y_train_cat = np.argmax(y_train, axis=1)
y_test_cat = np.argmax(y_test, axis=1)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train_cat, y_pred_cat)
cm_test = confusion_matrix(y_test_cat, y_pred_test_cat)

print(cm)
print(cm_test)

[[ 8  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0]
 [ 0  0 16  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  8  0  0]
 [ 0  0  0  0  0  3  0]
 [ 6  0  0  0  0  0  0]]
[[2 0 0 0 0 0]
 [0 7 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 1 0]
 [2 0 0 0 0 0]]


In [11]:
cm_count=0
cm_wrong=0
for i in range(len(cm)):
    cm_count += cm[i,i]
    for v in range(len(cm)):
        cm_wrong += cm[i,v]
cm_wrong -= cm_count
    
cm_test_count=0
cm_test_wrong=0
for i in range(len(cm_test)):
    cm_test_count += cm_test[i,i]
    for v in range(len(cm_test)):
        cm_test_wrong += cm_test[i,v]
cm_test_wrong -= cm_test_count

accuracy = cm_count/(cm_count + cm_wrong)
accuracy_test = cm_test_count/(cm_test_count + cm_test_wrong)

print(accuracy)
print(accuracy_test)

0.925
0.9047619047619048
